In [1]:
import xarray as xr
import numpy as np

In [2]:
@xr.register_dataarray_accessor("GridData")
class GridData(object):
    def __init__(self, data, coords, dims):
        self._obj = xr.DataArray(data=data,coords=coords,dims=dims)
        self._nx = None
    
    @property
    def nx(self):
        if self._nx is None:
            self._nx = len(self._obj.coords['x'])
        return self._nx

    

15

In [6]:
b = a.GridData.nx

In [3]:
#import xarray as xr
import numpy as np

xs = np.linspace(0,1.0,15)
ys = np.linspace(0,1.0,16)
zs = np.linspace(0,1.0,17)

xs2 = np.linspace(0,1.2,32)

data = np.random.normal(size=(len(xs),len(ys),len(zs)))
data_1d = np.arange(len(xs2))

In [4]:
a = xr.DataArray(name='lwc',data=data,coords=[xs,ys,zs], dims=['x','y','z'])

In [42]:
b = xr.DataArray(name='reff',data=data_1d,coords=[xs2],dims=['x'])

In [45]:
new = xr.merge([a,b])

array([0.        , 0.03870968, 0.07741935, 0.11612903, 0.15483871,
       0.19354839, 0.23225806, 0.27096774, 0.30967742, 0.3483871 ,
       0.38709677, 0.42580645, 0.46451613, 0.50322581, 0.54193548,
       0.58064516, 0.61935484, 0.65806452, 0.69677419, 0.73548387,
       0.77419355, 0.81290323, 0.8516129 , 0.89032258, 0.92903226,
       0.96774194, 1.00645161, 1.04516129, 1.08387097, 1.12258065,
       1.16129032, 1.2       ])

In [56]:
new.coords['x']

<xarray.DataArray 'x' (x: 46)>
array([0.      , 0.03871 , 0.071429, 0.077419, 0.116129, 0.142857, 0.154839,
       0.193548, 0.214286, 0.232258, 0.270968, 0.285714, 0.309677, 0.348387,
       0.357143, 0.387097, 0.425806, 0.428571, 0.464516, 0.5     , 0.503226,
       0.541935, 0.571429, 0.580645, 0.619355, 0.642857, 0.658065, 0.696774,
       0.714286, 0.735484, 0.774194, 0.785714, 0.812903, 0.851613, 0.857143,
       0.890323, 0.928571, 0.929032, 0.967742, 1.      , 1.006452, 1.045161,
       1.083871, 1.122581, 1.16129 , 1.2     ])
Coordinates:
  * x        (x) float64 0.0 0.03871 0.07143 0.07742 ... 1.084 1.123 1.161 1.2

In [69]:
new2 = b.combine_first(a)

In [74]:
new2[2]

<xarray.DataArray 'reff' (y: 16, z: 17)>
array([[ 1.25830528e+00,  9.42694963e-01, -1.21963872e+00,
         1.46923945e+00,  1.08082215e+00,  1.22128677e+00,
        -1.21775920e+00,  1.86886255e+00,  1.26587677e+00,
        -1.48642881e+00, -2.80487612e-01, -3.90291889e-01,
         6.62228239e-01,  8.17975747e-01, -1.36590883e-01,
        -1.61280087e+00, -9.80509860e-01],
       [-6.53659059e-01,  1.34168328e-01,  3.24448623e-01,
         1.22111284e+00,  1.56163156e+00, -4.68906219e-01,
        -7.59086806e-01, -2.15931238e+00,  1.08345118e+00,
        -7.31787954e-01,  9.84876177e-01, -1.71045237e+00,
         4.38234817e-01,  1.19995581e+00,  1.14232462e+00,
         5.28472263e-01, -6.94899848e-01],
       [ 2.25529670e-01,  7.56189038e-01,  8.53668496e-01,
         7.08884916e-01, -1.51094282e-01,  9.93361491e-01,
        -8.29997599e-02, -2.24058602e+00, -1.23346364e+00,
        -3.22603721e-01,  1.84813985e+00, -2.23351981e+00,
        -2.10105394e-01, -1.30387830e+00, -6.88114779e-01,
         9.25254017e-01, -8.41970168e-02],
       [-6.03070308e-01, -3.67016565e-01, -1.55615052e+00,
         1.11603346e+00,  2.71643870e+00,  2.16246670e+00,
         5.12211218e-01, -3.97903153e-01, -1.00969442e-01,
         7.11811788e-01,  1.46537863e+00, -9.41120942e-01,
        -5.34846569e-01,  1.96482209e-01,  1.73421149e+00,
        -9.31128316e-01, -5.01348852e-01],
       [-1.27726931e+00,  6.66692239e-01, -2.48060383e-01,
        -9.78527749e-01,  7.20749663e-01, -1.29689084e+00,
         7.94349635e-01, -1.59421985e-01,  7.74139487e-01,
        -1.33723356e+00, -1.33983765e-02, -6.60330089e-01,
        -2.12794761e+00,  4.57279572e-01, -1.80945764e+00,
         1.00524904e+00,  2.64758180e-01],
       [ 7.93673979e-02,  3.50196097e+00,  2.77515567e-01,
         2.29688138e+00,  2.84625970e-01, -2.83459211e-01,
         2.47518442e-01,  2.54617886e-01,  9.99326371e-01,
         5.67662096e-01, -2.21863905e+00,  2.07441852e+00,
        -3.09172284e-01, -7.33740914e-01, -1.18431689e+00,
        -4.50775638e-01,  1.35982630e+00],
       [ 1.96024497e-01, -4.21106326e-01, -1.14319629e+00,
        -7.04894959e-01, -9.53631994e-01,  5.11301413e-01,
         1.17137722e-01,  1.54761353e+00,  3.19806621e-01,
        -1.73583635e+00,  1.89421980e-01,  1.57357653e-01,
        -1.51144065e+00,  4.48384787e-01, -1.73368942e-01,
         1.74279206e+00,  4.28964527e-03],
       [-1.88377306e+00, -1.32217769e+00,  1.57163867e+00,
        -4.98589192e-02, -1.16352999e+00, -7.91842811e-01,
         6.75933100e-01, -1.12264034e-02,  4.96353396e-01,
         9.82669926e-01, -6.44955364e-02,  9.19975305e-01,
        -3.34796081e-01, -2.07002305e-01,  2.68257478e-01,
        -1.78384286e+00,  1.02984400e+00],
       [ 1.43573682e+00, -2.57735981e-01, -2.87880264e-01,
        -1.91100326e-03,  1.13593162e+00,  3.56847632e-01,
        -5.78056622e-02, -7.06417874e-01, -7.45704640e-01,
        -5.41258241e-01,  1.92195236e+00,  4.57060608e-01,
         7.92996202e-01,  2.11685954e-01, -1.41453834e+00,
         7.03623985e-01,  7.77620408e-01],
       [ 1.99615878e-02, -2.14449555e-01, -1.68322602e+00,
        -1.33036559e-01,  9.58575216e-02, -4.70520821e-01,
        -4.30465732e-01, -4.84951611e-01, -2.06962410e-01,
        -6.67317560e-02,  3.23273923e-01, -6.15455877e-01,
        -7.89882406e-01,  2.26982182e-01,  5.38236997e-01,
         1.74771059e+00, -8.86808079e-01],
       [-1.62884018e+00, -5.73427014e-01,  4.46649149e-02,
        -9.37903271e-01,  9.52996678e-01,  1.17209631e+00,
         1.22615413e+00, -1.43556939e+00, -2.89578253e-01,
        -6.44153100e-01,  1.34795789e+00, -4.71965599e-01,
         1.48041839e+00,  1.97990011e+00, -1.28690433e+00,
         1.01796737e+00,  1.35081085e-01],
       [-4.86714439e-01,  4.05807304e-01,  1.63660377e+00,
        -4.85738414e-01,  6.82106529e-01, -2.17199084e+00,
         7.58456920e-01,  8.54997553e-01,  9.06315078e-01,
         6.31724017e-01,  4.81335468e-01,  1.53688303e-01,
     